version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: student-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: student-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017
    volumes:
      - .:/app
    restart: always

volumes:
  mongo-data:
